name: Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd store-server
          pip install -r requirements.txt
      - name: Lint
        run: |
          pip install black ruff
          cd store-server
          black --check .
          ruff check .
      - name: Test
        run: |
          cargo install just
          cd store-server && just test
